# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d31c6aa76418cab4ea772fe8a92d6464e8c753e9f6cb0ceef77f733ab2d5cd11bc561607a83c33eef07eb4e116dcca1a972fec333ecc98b3fadc7288da9e80a1

test:
  secret_key_base: 669c5d7b3c289b4a1b1a085349d57a69b4b8aa7becf17a6455f6b7c07672d949417810c95fa04f456a8f8b28a2c0a196991e8896509a31b82656678695c6c994

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_token: <% ENV["SECRET_TOKEN"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
